{
 "title": "CRDB Console: Changefeeds",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Max Changefeed Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_max_behind_nanos{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Max Changefeed Latency"
    }
   ]
  },
  {
   "title": "Sink Byte Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_bytes{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Emitted Bytes"
    }
   ]
  },
  {
   "title": "Sink Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Messages"
    },
    {
     "expr": "sum(rate(changefeed_flushes{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "Sink Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Message Emit Time"
    },
    {
     "expr": "sum(rate(changefeed_flush_nanos{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Flush Time"
    }
   ]
  },
  {
   "title": "Changefeed Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jobs_changefeed_resume_retry_error{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Retryable Errors"
    }
   ]
  }
 ]
}