{
 "title": "CRDB Console: Distributed",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_batches{agent=\"cockroachdb\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "Batch"
    },
    {
     "expr": "sum(rate(distsender_batches_partial{agent=\"cockroachdb\"}[$__rate_interval])) by (cluster)",
     "legendFormat": "Partial Batches"
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "RPCs Sent"
    },
    {
     "expr": "sum(rate(distsender_rpc_sent_local{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Local Fast-path"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent_nextreplicaerror{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Replica Errors"
    },
    {
     "expr": "sum(rate(distsender_errors_notleaseholder{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Not Lease Holder Errors"
    }
   ]
  },
  {
   "title": "KV Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(txn_commits{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(txn_commits1PC{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Fast-path Committed"
    },
    {
     "expr": "sum(rate(txn_aborts{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Aborted"
    }
   ]
  },
  {
   "title": "KV Transaction Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(txn_restarts_writetooold{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Write Too Old"
    },
    {
     "expr": "sum(rate(txn_restarts_writetoooldmulti{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Write Too Old (multiple)"
    },
    {
     "expr": "sum(rate(txn_restarts_serializable{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Forwarded Timestamp (iso=serializable)"
    },
    {
     "expr": "sum(rate(txn_restarts_asyncwritefailure{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Async Consensus Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_readwithinuncertainty{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Read Within Uncertainty Interval"
    },
    {
     "expr": "sum(rate(txn_restarts_txnaborted{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(rate(txn_restarts_txnpush{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Push Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_unknown{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "KV Transactional Durations: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of transaction durations over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(txn_durations_bucket{agent=\"cockroachdb\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Transaction Durations: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of transaction durations over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(txn_durations_bucket{agent=\"cockroachdb\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 99th percentile ",
   "type": "timeseries",
   "description": "The 99th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(liveness_heartbeatlatency_bucket{agent=\"cockroachdb\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(liveness_heartbeatlatency_bucket{agent=\"cockroachdb\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}