{
 "title": "CRDB Console: Slow Requests",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Slow Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_raft{agent=\"cockroachdb\"})",
     "legendFormat": "Slow Raft Proposals"
    }
   ]
  },
  {
   "title": "Slow DistSender RPCs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_distsender{agent=\"cockroachdb\"})",
     "legendFormat": "Slow DistSender RPCs"
    }
   ]
  },
  {
   "title": "Slow Lease Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_lease{agent=\"cockroachdb\"})",
     "legendFormat": "Slow Lease Acquisitions"
    }
   ]
  },
  {
   "title": "Slow Latch Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_slow_latch{agent=\"cockroachdb\"})",
     "legendFormat": "Slow Latch Acquisitions"
    }
   ]
  }
 ]
}