{
 "title": "CRDB Console: SQL",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Open SQL Sessions",
   "type": "timeseries",
   "description": "The total number of open SQL Sessions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sql_conns{agent=\"cockroachdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open SQL Transactions",
   "type": "timeseries",
   "description": "The total number of SQL transactions currently open.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sql_txns_open{agent=\"cockroachdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active SQL Statements",
   "type": "timeseries",
   "description": "The total number of SQL statements currently running.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sql_distsql_queries_active{agent=\"cockroachdb\"})",
     "legendFormat": "Active Statements"
    }
   ]
  },
  {
   "title": "SQL Byte Traffic",
   "type": "timeseries",
   "description": "The total amount of SQL client network traffic in bytes per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(rate(sql_bytesout{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "SQL Statements",
   "type": "timeseries",
   "description": "A moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "SQL Statement Errors",
   "type": "timeseries",
   "description": "The number of statements which returned a planning or runtime error.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "SQL Statement Contention",
   "type": "timeseries",
   "description": "The total number of SQL statements that experienced contention.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_distsql_contended_queries_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Contention"
    }
   ]
  },
  {
   "title": "Active Flows for Distributed SQL Statements",
   "type": "timeseries",
   "description": "The number of flows on each node contributing to currently running distributed SQL statements.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sql_distsql_flows_active{agent=\"cockroachdb\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 99th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 90th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 90% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(sql_service_latency_bucket{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of latency between query requests and responses over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(exec_latency_bucket{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of latency between query requests and responses over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(exec_latency_bucket{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "The total number of transactions initiated, committed, rolled back, or aborted per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate( sql_txn_rollback_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "Aborts"
    }
   ]
  },
  {
   "title": "Transaction Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of total transaction time over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(sql_txn_latency_bucket{agent=\"cockroachdb\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of total transaction time over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(sql_txn_latency_bucket{agent=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Memory",
   "type": "timeseries",
   "description": "The current amount of allocated SQL memory. This amount is what is compared against the node's --max-sql-memory flag.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sql_mem_root_current{agent=\"cockroachdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schema Changes",
   "type": "timeseries",
   "description": "The total number of DDL statements per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{agent=\"cockroachdb\"}[$__rate_interval]))  ",
     "legendFormat": "DDL Statements"
    }
   ]
  },
  {
   "title": "Statement Denials: Cluster Settings",
   "type": "timeseries",
   "description": "The total number of statements denied per second due to a [cluster setting](https://www.cockroachlabs.com/docs/v21.1/cluster-settings.html) in the format feature.statement_type.enabled = FALSE.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sql_feature_flag_denial{agent=\"cockroachdb\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}