{
 "title": "fio_exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "read_kb{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Read - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(read_kb{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "write_kb{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Write - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_kb{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "read_iops{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read IOPS - Change Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(read_iops{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "write_iops{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write IOPS - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_iops{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Submission Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "read_slat_min{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "read_slat_max{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "read_slat_mean{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Read Submission Latency - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(read_slat_min{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "irate(read_slat_max{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "irate(read_slat_mean{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Write Submission Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "write_slat_min{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "write_slat_max{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "write_slat_mean{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Write Submission Latency - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_slat_min{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "irate(write_slat_max{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "irate(write_slat_mean{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "read_bandwidth{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Bandwidth - Change Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(read_bandwidth{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "write_bandwidth{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Bandwidth - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_bandwidth{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Completion Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "read_clat_min{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "read_clat_max{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "read_clat_mean{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Read Completion Latency - Change Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(read_clat_min{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "irate(read_clat_max{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "irate(read_clat_mean{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Write Completion Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "write_clat_min{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "write_clat_max{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "write_clat_mean{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Write Completion Latency - Change Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_clat_min{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Min"
    },
    {
     "expr": "irate(write_clat_max{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Max"
    },
    {
     "expr": "irate(write_clat_mean{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Mean"
    }
   ]
  },
  {
   "title": "Read Completion Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "read_clat_pct12{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} %95"
    },
    {
     "expr": "read_clat_pct13{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} 99%"
    }
   ]
  },
  {
   "title": "Read Completion Percentile Latency - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(read_clat_pct12{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} %95"
    },
    {
     "expr": "irate(read_clat_pct13{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} 99%"
    }
   ]
  },
  {
   "title": "Write Completion Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "write_clat_pct12{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} %95"
    },
    {
     "expr": "write_clat_pct13{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} 99%"
    }
   ]
  },
  {
   "title": "Write Completion Percentile Latency - Change Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_clat_pct12{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} %95"
    },
    {
     "expr": "irate(write_clat_pct13{job=\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} 99%"
    }
   ]
  }
 ]
}