{
 "title": "Kubernetes cluster monitoring (via Prometheus) New-Features",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "frisbee"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "query": "30s, 1m,10m,30m,1h,6h" }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "count(max(up) by (node))", "legendFormat": "nodes" }
   ]
  },
  {
   "title": "Total Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max (machine_memory_bytes) by (node))"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max (container_fs_limit_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}) by (node)) != 0"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up) by (node)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(up) by (instance, node)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Running Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "count(max(up) by (instance))" }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(machine_cpu_cores) by (node))"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max (container_fs_usage_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}) by (node))"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{node=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{node=~\"$node\"} - container_memory_usage_bytes{node=~\"$node\"}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Placement Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "max(up) by (node, instance)" }
   ]
  },
  { "title": "Node Overview ($node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>Overview for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{node=~\"$node\"}) / max (machine_memory_bytes{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node CPU  usage ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", id=\"/\"}[$interval]))  / max (machine_cpu_cores{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max(container_fs_usage_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}))  / \nsum(max(container_fs_limit_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}))) * 100\n"
    }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_fs_limit_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max (machine_memory_bytes{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", id=\"/\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max (machine_cpu_cores{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(container_fs_usage_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (container_fs_limit_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}))"
    }
   ]
  },
  { "title": "CPU Metrics for $instance ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>CPU metrics for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage (avg $interval)",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval]) * 100 != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Breakdown CPU Usage (avg $interval)",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])) by (instance) * 100  != 0 ",
     "legendFormat": "{{instance}} (Kernel)"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])) by (instance) * 100  != 0  ",
     "legendFormat": "{{instance}} (Userspace)"
    }
   ]
  },
  { "title": "Memory Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>Memory metrics for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage (max $interval)",
   "type": "timeseries",
   "description": "Current memory usage, this includes all memory regardless of when it was accessed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time(container_memory_usage_bytes{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])  != 0",
     "legendFormat": "{{instance}} (Used)"
    }
   ]
  },
  {
   "title": "Breakdown Virtual Memory Usage (max $interval)",
   "type": "timeseries",
   "description": "hot:  The amount of working set memory, this includes recently accessed memory,  dirty memory, and kernel memory. \n\nswap: The amount of swap currently used by the processes in this cgroup\nmmap: \tThe amount of memory used for mapped files (includes tmpfs/shmem)\n\ncache:  Number of bytes of page cache memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time(container_memory_working_set_bytes{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])   != 0",
     "legendFormat": "{{instance}} (Hot)"
    },
    {
     "expr": "max_over_time(container_memory_mapped_file{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])  != 0\n",
     "legendFormat": "{{instance}} (Mmap)"
    },
    {
     "expr": "max_over_time(container_memory_cache{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])  != 0",
     "legendFormat": "{{instance}} (Cache)"
    },
    {
     "expr": "max_over_time(container_memory_swap{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])  != 0",
     "legendFormat": "{{instance}} (Swap)"
    }
   ]
  },
  {
   "title": "Page Faults (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{node=~\"^$node\", id=\"/\", instance=~\"$instance\", failure_type=\"pgfault\"}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OOM-Killer events (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_oom_events_total{node=~\"$node\", id=\"/\", instance=\"$instance\"}[$interval]) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "I/O Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 82 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>Block I/O metrics for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Accessed Bytes / Throughput  (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{ node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance) != 0",
     "legendFormat": "{{instance}}  (Write)"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\",  device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}} (Read)"
    }
   ]
  },
  {
   "title": "IOPS In Progress ",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_fs_io_current{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"} != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed IOPS (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}} (Read)"
    }
   ]
  },
  {
   "title": "Accessed Sectors (avg $interval)",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_sector_writes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\", }[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_sector_reads_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay.*)|(/dev/mapper.*)|(/dev/[a-zA-Z0-9]+)$\",}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}} (Read)"
    }
   ]
  },
  {
   "title": "I/O Queue wait time (avg $interval)",
   "type": "timeseries",
   "description": "io_time:\nThis value counts the number of milliseconds during which the device has had I/O requests queued.\n\nweighted_io_time:\nThis value counts the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, this value will increase as the product of the number of milliseconds times the number of requests waiting ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_io_time_weighted_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\",  device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "I/O Queue wait time Breakdown (avg $interval)",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_write_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\", }[$interval])) by (instance) != 0",
     "legendFormat": "{{instance}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_read_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\",}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}} (Read)"
    }
   ]
  },
  {
   "title": "Merged I/O Operations (avg $interval)",
   "type": "timeseries",
   "description": "Reads and writes which are adjacent to each other may be merged for efficiency. Thus, two 4K reads may become one 8K read before it is ultimately handed to the disk, and so it will be counted (and queued) as only one I/O. These fields lets you know how often this was done.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_merged_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\", }[$interval])) by (instance) != 0",
     "legendFormat": "{{instance}}  (Write)"
    },
    {
     "expr": "- sum(rate(container_fs_reads_merged_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\",}[$interval])) by (instance)  != 0",
     "legendFormat": "{{instance}} (Read)"
    }
   ]
  },
  {
   "title": "Completed I/O Size (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance)  / sum(rate(container_fs_writes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance) != 0",
     "legendFormat": "{{instance}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance)  / sum(rate(container_fs_reads_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance) != 0",
     "legendFormat": "{{instance}} (Read)"
    }
   ]
  },
  {
   "title": "Disk Throughput (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$interval])) by (instance, operation) != 0",
     "legendFormat": "{{instance}}  ({{operation}})"
    }
   ]
  },
  { "title": "Network Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "Network Throughput (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": " sum(rate(container_network_transmit_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])) by (instance) != 0",
     "legendFormat": "TX: {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])) by (instance) != 0",
     "legendFormat": "RX: {{instance}} "
    }
   ]
  },
  {
   "title": "Network Packet Drops (avg $interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])) by (instance) != 0",
     "legendFormat": "TX: {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_receive_packets_dropped_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$interval])) by (instance ) != 0",
     "legendFormat": "RX: {{instance}} "
    }
   ]
  }
 ]
}