{
 "title": "Frisbee SUT Monitoring (Analytics)",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "frisbee"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(node)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$node\"}) / max (machine_memory_bytes{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": " CPU  usage ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", id=\"/\"}[$__rate_interval])) / sum(max(machine_cpu_cores{node=~\"$node\"}) by (node)) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max(container_fs_usage_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}))  / \nsum(max(container_fs_limit_bytes{node=~\"$node\",id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}))) * 100\n"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "count(max(up) by (node))", "legendFormat": "nodes" }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "count(max(up) by (instance))" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up) by (node)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max (machine_memory_bytes{node=~\"$node\"}))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", id=\"/\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(machine_cpu_cores) by (node))"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(container_fs_usage_bytes{node=~\"$node\", id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (container_fs_limit_bytes{node=~\"$node\", id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{node=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{node=~\"$node\"} - container_memory_usage_bytes{node=~\"$node\"}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Placement Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "max(up) by (node, instance)" }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_fs_limit_bytes{node=~\"$node\", id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance, device)",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "CPU Metrics for $instance ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>CPU metrics for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])  != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Breakdown CPU Usage ",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance)   != 0 ",
     "legendFormat": "{{instance}} (Kernel)"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance)   != 0  ",
     "legendFormat": "{{instance}} (Userspace)"
    }
   ]
  },
  { "title": "Memory Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>Memory metrics for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage ",
   "type": "timeseries",
   "description": "Current memory usage, this includes all memory regardless of when it was accessed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{node=~\"$node\", id=\"/\", instance=~\"$instance\"}  != 0",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Hot Memory Usage",
   "type": "timeseries",
   "description": "hot:  The amount of working set memory, this includes recently accessed memory,  dirty memory, and kernel memory. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{node=~\"$node\", id=\"/\", instance=~\"$instance\"}   != 0",
     "legendFormat": "{{instance}} (Hot)"
    }
   ]
  },
  {
   "title": "Memory Mapped File Usage",
   "type": "timeseries",
   "description": "mmap: \tThe amount of memory used for mapped files (includes tmpfs/shmem)\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_mapped_file{node=~\"$node\", id=\"/\", instance=~\"$instance\"}  != 0",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "timeseries",
   "description": "cache:  Number of bytes of page cache memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_cache{node=~\"$node\", id=\"/\", instance=~\"$instance\"}  != 0",
     "legendFormat": "{{instance}} (Cache)"
    }
   ]
  },
  {
   "title": "Swap Memory Usage",
   "type": "timeseries",
   "description": "swap: The amount of swap currently used by the processes in this cgroup",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_swap{node=~\"$node\", id=\"/\", instance=~\"$instance\"}  != 0",
     "legendFormat": "{{instance}} (Swap)"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{node=~\"^$node\", id=\"/\", instance=~\"$instance\", failure_type=\"pgfault\"}[$__rate_interval])) by (instance)  != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OOM-Killer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_oom_events_total{node=~\"$node\", id=\"/\", instance=\"$instance\"}[$__rate_interval]) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "I/O Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 107 },
   "options": {
    "content": "<h1><i><font color=#5991A7><b><center>Block I/O metrics for </font><font color=#e68a00>$node</font> <font color=#5991A7> </center></b></font></i></h1>"
   },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Filesystem Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{ node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance,device) != 0",
     "legendFormat": "{{instance}}:{{device}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\",  device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance, device)  != 0",
     "legendFormat": "{{instance}}:{{device}}  (Read)"
    }
   ]
  },
  {
   "title": "BlockDevice Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_blkio_device_usage_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance, device, operation) != 0",
     "legendFormat": "{{instance}}:{{device}}  ({{operation}})"
    }
   ]
  },
  {
   "title": "Completed IOPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mappper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance,device)  != 0",
     "legendFormat": "{{instance}}:{{device}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mappper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance,device)  != 0",
     "legendFormat": "{{instance}}:{{device}} (Read)"
    }
   ]
  },
  {
   "title": "Completed I/O Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance, device)  / sum(rate(container_fs_writes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance, device) != 0",
     "legendFormat": "{{instance}}:{{device}} (Write)"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance, device)  / sum(rate(container_fs_reads_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval])) by (instance, device) != 0",
     "legendFormat": "{{instance}}:{{device}}  (Read)"
    }
   ]
  },
  {
   "title": "Accessed Sectors ",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_sector_writes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\", }[$__rate_interval])) by (instance,device)  != 0",
     "legendFormat": "{{instance}}:{{device}} (Write)"
    },
    {
     "expr": "sum(rate(container_fs_sector_reads_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay.*)|(/dev/mapper.*)|(/dev/[a-zA-Z0-9]+)$\",}[$__rate_interval])) by (instance, device)  != 0",
     "legendFormat": "{{instance}}:{{device}} (Read)"
    }
   ]
  },
  {
   "title": "IOPS In Progress ",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_fs_io_current{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"} != 0",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "I/O Queue wait time",
   "type": "heatmap",
   "description": "io_time:\nThis value counts the number of milliseconds during which the device has had I/O requests queued.\n\nweighted_io_time:\nThis value counts the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, this value will increase as the product of the number of milliseconds times the number of requests waiting ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_io_time_weighted_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\",  device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\"}[$__rate_interval]))  != 0",
     "legendFormat": "{{instance}}:{{device}} "
    }
   ]
  },
  {
   "title": "I/O Queue wait time Breakdown",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_write_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\", }[$__rate_interval])) by (instance,device) != 0",
     "legendFormat": "{{instance}}:{{device}}  (Write)"
    },
    {
     "expr": "sum(rate(container_fs_read_seconds_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\",}[$__rate_interval])) by (instance,device)  != 0",
     "legendFormat": "{{instance}}:{{device}} (Read)"
    }
   ]
  },
  {
   "title": "Merged I/O Operations",
   "type": "timeseries",
   "description": "Reads and writes which are adjacent to each other may be merged for efficiency. Thus, two 4K reads may become one 8K read before it is ultimately handed to the disk, and so it will be counted (and queued) as only one I/O. These fields lets you know how often this was done.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_merged_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\", }[$__rate_interval])) by (instance, device) != 0",
     "legendFormat": "{{instance}}:{{device}}  (Write)"
    },
    {
     "expr": "- sum(rate(container_fs_reads_merged_total{node=~\"$node\", id=\"/\", instance=~\"$instance\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[a-zA-Z0-9]+)$\",}[$__rate_interval])) by (instance,device)  != 0",
     "legendFormat": "{{instance}}:{{device}} (Read)"
    }
   ]
  },
  { "title": "Network Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 } },
  {
   "title": "Network Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": " sum(rate(container_network_transmit_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance, interface) != 0",
     "legendFormat": "{{instance}}:{{interface}} TX"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance, interface) != 0",
     "legendFormat": "{{instance}}:{{interface}} RX"
    }
   ]
  },
  {
   "title": "Network Packet ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance,interface) != 0",
     "legendFormat": "{{instance}}:{{interface}} TX"
    },
    {
     "expr": "- sum(rate(container_network_receive_packets_total{node=~\"$node\", id=\"/\", instance=~\"$instance\"}[$__rate_interval])) by (instance,interface ) != 0",
     "legendFormat": "{{instance}}:{{interface}} RX"
    }
   ]
  }
 ]
}