{
 "title": "Frisbee SUT Monitoring (Singleton)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Infrastructure Overview ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Placement Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    { "expr": "max(up) by (node, instance)" }
   ]
  },
  {
   "title": "Scenario Events",
   "type": "annolist",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "targets": [
    { "expr": "container_memory_usage_bytes{}", "legendFormat": "Used" },
    {
     "expr": "sum(container_spec_memory_limit_bytes{} - container_memory_usage_bytes{}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "container_memory_usage_bytes{}", "legendFormat": "Used" },
    {
     "expr": "sum(container_spec_memory_limit_bytes{} - container_memory_usage_bytes{}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  { "title": "__CPU Section__", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Utilization [ Userspace/Kernelspace  ]",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization [  Userspace  ]",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization [  Kernelspace  ]",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "__Memory Section__", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Memory Usage (All types)",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})  by (instance) != 0",
     "legendFormat": "{{instace}}"
    }
   ]
  },
  {
   "title": "Memory Mapped Files",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_memory_mapped_file{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instace}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_memory_failures_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "__IO Section__", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Total Data Transfers (Bytes)",
   "type": "bargauge",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(container_fs_writes_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device)  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "max(container_fs_reads_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Total Data Transfers (Bytes)",
   "type": "piechart",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(container_fs_writes_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device)  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "max(container_fs_reads_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Total I/O Operations",
   "type": "bargauge",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(container_fs_writes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device)  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "max(container_fs_reads_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Total I/O Operations",
   "type": "piechart",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(container_fs_writes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device)  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "max(container_fs_reads_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) by (instance, device) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_fs_writes_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance, device) != 0",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "IO Throughput (Write)",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_writes_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Throughput (Read)",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS (Write)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_writes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS (Read)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_reads_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Estimated IO Request Size (Write)",
   "type": "timeseries",
   "description": "I/O request size which is also referred as block size is the size of request that application uses to perform I/O operation on storage device. Every application uses a different I/O request size and based on how big the request size is, it can have pretty good impact on storage performance.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_writes_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])   / rate(container_fs_writes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Estimated IO Request Size (Read)",
   "type": "timeseries",
   "description": "I/O request size which is also referred as block size is the size of request that application uses to perform I/O operation on storage device. Every application uses a different I/O request size and based on how big the request size is, it can have pretty good impact on storage performance.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])   / rate(container_fs_reads_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cummulative Time spent in IO (Write)",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(container_fs_write_seconds_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^/dev/mapper/.*$\"}) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cummulative Time spent in IO (Read)",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(container_fs_read_seconds_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^/dev/mapper/.*$\"})  by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "__Network__", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Total Network Traffic (Bytes)",
   "type": "bargauge",
   "description": "Cumulative count of bytes transmitted/received.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(container_network_transmit_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(max(container_network_receive_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Total Network Traffic (Bytes)",
   "type": "piechart",
   "description": "Cumulative count of bytes transmitted/received.",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(container_network_transmit_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(max(container_network_receive_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Total Network Traffic (Operations)",
   "type": "bargauge",
   "description": "Cumulative count of packets transmitted/received",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(container_network_transmit_packets_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(max(container_network_receive_packets_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Total Network Traffic (Operations)",
   "type": "piechart",
   "description": "Cumulative count of packets transmitted/received",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(container_network_transmit_packets_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(max(container_network_receive_packets_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"})) != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Inbound Network Traffic",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound Network Traffic (Packets)",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_packets_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound Network Traffic (Packets)",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_packets_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\"}[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "__Rare Section__", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 } },
  {
   "title": "OOM-Killer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Sectors Written",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. \n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_sector_writes_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sectors Read",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. \n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_sector_reads_total{id=\"/\", instance=~\"$Instance\", node=~\"$Node\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval])) by (instance) != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}