{
 "title": "Frisbee SUT Monitoring (Summary)",
 "tags": [
  "kubernetes",
  "frisbee"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Infrastructure Overview ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(container_memory_working_set_bytes) by (instance)) / sum(avg(machine_memory_bytes) by (node)) * 100"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval])) / sum(max(machine_cpu_cores) by (node))) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(max(container_fs_usage_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))  / \nsum(max(container_fs_limit_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))) * 100\n"
    }
   ]
  },
  {
   "title": "Service Placement",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(max(up) by (instance, node)) by (node)"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(max(up{}) by (instance))" }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(max(up{}) by (node))" }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max(container_memory_working_set_bytes{id=\"/\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(machine_memory_bytes) by (node)"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max(machine_cpu_cores) by (node)) != 0"
    }
   ]
  },
  {
   "title": "Capacity Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max(container_fs_usage_bytes{device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Capacity Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (container_fs_limit_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    { "expr": "container_memory_usage_bytes{}", "legendFormat": "Used" },
    {
     "expr": "sum(container_spec_memory_limit_bytes{} - container_memory_usage_bytes{}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Placement Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "targets": [
    { "expr": "max(up) by (node, instance)" }
   ]
  },
  {
   "title": "Scenario Events",
   "type": "annolist",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 10 },
   "targets": [
    { "expr": "container_memory_usage_bytes{}", "legendFormat": "Used" },
    {
     "expr": "sum(container_spec_memory_limit_bytes{} - container_memory_usage_bytes{}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "CPU/IO/Net Usage",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval])) != 0 ",
     "legendFormat": "cpu"
    },
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{id=\"/\"}[$__rate_interval]) +  \nrate(container_fs_writes_bytes_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "io"
    },
    {
     "expr": "avg(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]) +  \nrate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "net"
    }
   ]
  },
  {
   "title": "__CPU Section__",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization [ Min / Avg / Max ]",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "CPU Utilization [  User / Kernel ]",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "kernel"
    },
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "CPU / RAM",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(rate(container_memory_working_set_bytes{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "__Memory Section__",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Memory Usage Per Type",
   "type": "timeseries",
   "description": "Usage: Current memory usage, including all memory regardless of when it was accessed\n\nWorking Set : refers to the amount of physical memory (RAM) the process uses. \n\nRSS: The amount of memory that doesn’t correspond to anything on disk: stacks, heaps, and anonymous memory maps.\n\nSWAP: \tThe amount of swap currently used by the processes in this cgroup.\n\nMMAP: Indicates the amount of memory mapped by the processes in the control group. It doesn’t give you information about how much memory is used; it rather tells you how it is used.\n\nCACHE: \tThe amount of memory used by the processes of this control group that can be associated precisely with a block on a block device. When you read from and write to files on disk, this amount increases. This is the case if you use “conventional” I/O (open, read, write syscalls) as well as mapped files (with mmap). It also accounts for the memory used by tmpfs mounts.\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{id=\"/\"})   != 0",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{id=\"/\"})   != 0",
     "legendFormat": "WorkingSet"
    },
    {
     "expr": "avg(container_memory_rss{id=\"/\"})   != 0",
     "legendFormat": "RSS"
    },
    {
     "expr": "avg(container_memory_swap{id=\"/\"})   != 0",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg(container_memory_mapped_file{id=\"/\"})   != 0",
     "legendFormat": "MMAP"
    },
    {
     "expr": "avg(container_memory_cache{id=\"/\"})   != 0",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "Memory Allocation (Page Faults / RAM )",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_memory_failures_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "PageFaults"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{id=\"/\"})  != 0",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "Indicate the number of times that a process of the cgroup triggered a “page fault” and a “major fault”, respectively. \n\nA page fault happens when a process accesses a part of its virtual memory space which is nonexistent or protected. The former can happen if the process is buggy and tries to access an invalid address (it is sent a SIGSEGV signal, typically killing it with the famous Segmentation fault message). The latter can happen when the process reads from a memory zone which has been swapped out, or which corresponds to a mapped file: in that case, the kernel loads the page from disk, and let the CPU complete the memory access. It can also happen when the process writes to a copy-on-write memory zone: likewise, the kernel preempts the process, duplicate the memory page, and resume the write operation on the process’s own copy of the page.\n\n “Major” faults happen when the kernel actually needs to read the data from disk. When it just duplicates an existing page, or allocate an empty page, it’s a regular (or “minor”) fault.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_memory_failures_total{id=\"/\", failure_type=\"pgfault\"}[$__rate_interval])) by (failure_type) != 0",
     "legendFormat": "{{failure_type}}"
    }
   ]
  },
  {
   "title": "__IO Section__",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_fs_writes_bytes_total{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance, device) != 0",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "IO Traffic (Bytes)",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_writes_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(container_fs_reads_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Total IO Traffic (Bytes)",
   "type": "piechart",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_writes_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(container_fs_reads_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IO Traffic (Operations)",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Total IO Traffic (Operations)",
   "type": "piechart",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"})  != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IO Throughput (Filesystem)",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_writes_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "IOPS (Filesystem)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "avg(rate(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Estimate IO Request Size",
   "type": "timeseries",
   "description": "I/O request size which is also referred as block size is the size of request that application uses to perform I/O operation on storage device. Every application uses a different I/O request size and based on how big the request size is, it can have pretty good impact on storage performance.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_fs_writes_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))   / avg(rate(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) ",
     "legendFormat": "Write"
    },
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))   / avg(rate(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) ",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Time spent in IO",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(container_fs_write_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }) != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "avg(container_fs_read_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "__Network Section__",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic (Bytes)",
   "type": "timeseries",
   "description": "Cumulative count of bytes transmitted/received.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{id=\"/\"})  != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{id=\"/\"})  != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Total Network Traffic (Bytes)",
   "type": "piechart",
   "description": "Cumulative count of bytes transmitted/received.",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{id=\"/\"})  != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(container_network_receive_bytes_total{id=\"/\"})  != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Network Traffic (Packets)",
   "type": "timeseries",
   "description": "Cumulative count of packets transmitted/received",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_packets_total{id=\"/\"}) != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(container_network_receive_packets_total{id=\"/\"}) != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Total Network Traffic (Packets)",
   "type": "piechart",
   "description": "Cumulative count of packets transmitted/received",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_packets_total{id=\"/\"}) != 0",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(container_network_receive_packets_total{id=\"/\"}) != 0",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Outbound Network Throughput",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Inbound Network Throughput",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Correlated Outbound Network Throughput",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "Packets"
    },
    {
     "expr": "avg(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Correlated Inbound Network Throughput",
   "type": "timeseries",
   "description": "\n\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "Throughput"
    },
    {
     "expr": "avg(rate(container_network_receive_packets_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "__Rare Section__",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OOM-Killer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Sectors Written",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. \n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_sector_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_sector_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_sector_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Sectors Read",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. \n\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_sector_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_sector_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_sector_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  }
 ]
}