{
 "title": "Frisbee SUT Monitoring (Summaries)",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [
  "kubernetes",
  "frisbee"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster Overview ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{}) / max (machine_memory_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ id=\"/\"}[$__rate_interval]))  / sum(max(machine_cpu_cores{}) by (node)) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(max(container_fs_usage_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))  / \nsum(max(container_fs_limit_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))) * 100\n"
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(max(up) by (node))", "legendFormat": "nodes" }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(max(up) by (instance))" }
   ]
  },
  {
   "title": "Service Placement",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max(up) by (instance, node)) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(machine_memory_bytes{}) by (node)) "
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ id=\"/\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(machine_cpu_cores{}) by (node)) "
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max(container_fs_usage_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max by (device) (container_fs_limit_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}))"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "container_memory_usage_bytes{}", "legendFormat": "Used" },
    {
     "expr": "sum(container_spec_memory_limit_bytes{} - container_memory_usage_bytes{}) by (instance) ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Placement Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "max(up) by (node, instance)" }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(container_fs_limit_bytes{id=\"/\",device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (instance, device)",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Kernel CPU Usage",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_system_seconds_total{id=\"/\"}[$__rate_interval]))  != 0 ",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_cpu_system_seconds_total{id=\"/\"}[$__rate_interval]))   != 0 ",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_cpu_system_seconds_total{id=\"/\"}[$__rate_interval]))   != 0 ",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Userspace CPU Usage ",
   "type": "timeseries",
   "description": "container_cpu_usage_seconds_total which gives you how long the CPU has been occupied. 1s = a single Core for a whole second.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_user_seconds_total{id=\"/\"}[$__rate_interval]))   != 0 ",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_cpu_user_seconds_total{id=\"/\"}[$__rate_interval]))  != 0 ",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_cpu_user_seconds_total{id=\"/\"}[$__rate_interval])) != 0 ",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "In-RAM Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Virtual Memory Usage ",
   "type": "timeseries",
   "description": "Current memory usage, this includes all memory regardless of when it was accessed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{id=\"/\"})  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(container_memory_usage_bytes{id=\"/\"})  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(container_memory_usage_bytes{id=\"/\"})  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Hot Memory Usage",
   "type": "timeseries",
   "description": "hot:  The amount of working set memory, this includes recently accessed memory,  dirty memory, and kernel memory. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{id=\"/\"} )  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{id=\"/\"})   != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(container_memory_working_set_bytes{id=\"/\"})   != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Cache Memory Usage",
   "type": "timeseries",
   "description": "cache:  Number of bytes of page cache memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_cache{id=\"/\"})  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(container_memory_cache{id=\"/\"}) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(container_memory_cache{id=\"/\"})  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_failures_total{id=\"/\", failure_type=\"pgfault\"}[$__rate_interval])) != 0",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Out-of-RAM Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "OOM-Killer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_oom_events_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Memory Mapped File  Usage",
   "type": "timeseries",
   "description": "mmap: \tThe amount of memory used for mapped files (includes tmpfs/shmem)\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_mapped_file{id=\"/\"})  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(container_memory_mapped_file{id=\"/\"})  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(container_memory_mapped_file{id=\"/\"}) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Swap Memory Usage",
   "type": "timeseries",
   "description": "hot:  The amount of working set memory, this includes recently accessed memory,  dirty memory, and kernel memory. \n\nswap: The amount of swap currently used by the processes in this cgroup\nmmap: \tThe amount of memory used for mapped files (includes tmpfs/shmem)\n\ncache:  Number of bytes of page cache memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(container_memory_swap{id=\"/\"})  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(container_memory_swap{id=\"/\"})  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(container_memory_swap{id=\"/\"})  != 0",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "I/O Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Operation Distribution",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(container_blkio_device_usage_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}) by (operation)  != 0",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_writes_bytes_total{ id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_writes_bytes_total{ id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_writes_bytes_total{ id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Read Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_reads_bytes_total{ id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_reads_bytes_total{ id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_reads_bytes_total{ id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "IOPS In Progress ",
   "type": "timeseries",
   "description": "This value counts the number of I/O requests that have been issued to the device driver but have not yet completed. It does not include I/O requests that are in the queue but not yet issued to the device driver",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(container_fs_io_current{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(container_fs_io_current{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(container_fs_io_current{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Completed Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))   != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Completed Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))  != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))   != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Avg I/O Req Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))   / sum(rate(container_fs_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval]))   / sum(rate(container_fs_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/[sv]d[a-z][1-9]*)$\"}[$__rate_interval])) != 0",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Max I/O Queue wait time",
   "type": "heatmap",
   "description": "io_time:\nThis value counts the number of milliseconds during which the device has had I/O requests queued.\n\nweighted_io_time:\nThis value counts the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, this value will increase as the product of the number of milliseconds times the number of requests waiting ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "max(rate(container_fs_io_time_weighted_seconds_total{id=\"/\",  device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\"}[$__rate_interval]))  != 0"
    }
   ]
  },
  {
   "title": "Write Queue wait time",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_write_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_write_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_write_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Read Queue wait time",
   "type": "timeseries",
   "description": "read_time & write_time:\nThese values count the number of milliseconds that I/O requests have waited on this block device. If there are multiple I/O requests waiting, these values will increase at a rate greater than 1000/second; for example, if 60 read requests wait for an average of 30 ms, the read_time field will increase by 60*30 = 1800.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_read_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }[$__rate_interval])) != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_read_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }[$__rate_interval])) != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_read_seconds_total{id=\"/\", device=~\"^/dev/mapper/.*$\", }[$__rate_interval])) != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Written Sectors",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_sector_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_sector_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))   != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_sector_writes_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Read Sectors",
   "type": "timeseries",
   "description": "Contains the number of 512-bytes sectors read and written by the processes member of the cgroup, device by device. ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_fs_sector_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(container_fs_sector_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))   != 0",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(container_fs_sector_reads_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)$\", }[$__rate_interval]))  != 0",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Merged I/O Operations",
   "type": "timeseries",
   "description": "Reads and writes which are adjacent to each other may be merged for efficiency. Thus, two 4K reads may become one 8K read before it is ultimately handed to the disk, and so it will be counted (and queued) as only one I/O. These fields lets you know how often this was done.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_merged_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[sv]d[a-z][1-9]*)$\", }[$__rate_interval])) by (instance, device) != 0",
     "legendFormat": "{{instance}}:{{device}}  (Write)"
    },
    {
     "expr": "- sum(rate(container_fs_reads_merged_total{id=\"/\", device=~\"^(^$)|(overlay_.*)|(/dev/mapper/.*)|(/dev/[sv]d[a-z][1-9]*)$\",}[$__rate_interval])) by (instance,device)  != 0",
     "legendFormat": "{{instance}}:{{device}} (Read)"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 } },
  {
   "title": "Network Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": " max(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "TX (max)"
    },
    {
     "expr": " avg(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "TX (avg)"
    },
    {
     "expr": " min(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "TX (min)"
    },
    {
     "expr": "- max(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "RX (max)"
    },
    {
     "expr": "- avg(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "RX (avg)"
    },
    {
     "expr": "- min(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "RX (min)"
    }
   ]
  },
  {
   "title": "Network Packet",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 267 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "TX (max)"
    },
    {
     "expr": "avg(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "TX (avg)"
    },
    {
     "expr": "min(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "TX (min)"
    },
    {
     "expr": "- max(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "RX (max)"
    },
    {
     "expr": "- avg(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval]))  != 0",
     "legendFormat": "RX (avg)"
    },
    {
     "expr": "-  min(rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval])) != 0",
     "legendFormat": "RX (min)"
    }
   ]
  }
 ]
}