{
 "title": "YCSB Services",
 "tags": [ "ycsb" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations Per Client",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(ycsb_count) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Operations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ycsb_count) by (operation)", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Total Operations (by Client)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "max(ycsb_count) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(max(ycsb_avg) by (instance))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(max(ycsb_99th) by (instance))",
     "legendFormat": "99th "
    },
    {
     "expr": "max(max(ycsb_999th) by (instance))",
     "legendFormat": "99.9th "
    },
    {
     "expr": "max(max(ycsb_9999th) by (instance))",
     "legendFormat": "99.99th "
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(max(ycsb_ops) by (instance))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "avg(ycsb_ops)", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Historical Clients Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput (Queries Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "avg(ycsb_ops) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "max(ycsb_avg) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tail Latency (99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_99th) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tail Latency (99.9)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_999th) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tail Latency (99.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_9999th) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Historical Operations Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "avg(ycsb_ops) by (operation)", "legendFormat": "{{operation}}" },
    { "expr": "avg(ycsb_ops)", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "max(ycsb_avg) by (operation)", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Tail Latency (99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_99th) by (operation)", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Tail Latency (99.9)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_999th) by (operation)", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Tail Latency (99.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(ycsb_9999th) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}