apiVersion: v1
entries:
  fio:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.229793163+02:00"
    dependencies:
    - name: observability
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: sysmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 1c302f35a72bba5a7132c3c4196bfcf79fbfca03befc618dc8f7ea0f09dfc759
    name: fio
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/fio-0.1.1.tgz
    version: 0.1.1
  frisbee:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.248611991+02:00"
    dependencies:
    - condition: chaos-mesh.enabled
      name: chaos-mesh
      repository: https://charts.chaos-mesh.org
      version: 2.0.3
    - condition: openebs.enabled
      name: openebs
      repository: https://openebs.github.io/charts
      version: 3.0.0
    description: Frisbee is a Kubernetes platform for exploring, testing, and benchmarking distributed applications.
    digest: 3fef9862ecbf6857f8a154d0756bce67d3d91d680c33e1d8c78f217c3d78c67b
    name: frisbee
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/frisbee-0.1.1.tgz
    version: 0.1.1
  iperf:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.249311758+02:00"
    dependencies:
    - name: observability
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: sysmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 94cf1b1f88341fdc1663425f26ca01abea109fb72ab61f23593c2a2cbe9e1194
    name: iperf
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/iperf-0.1.1.tgz
    version: 0.1.1
  mongodb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.250371169+02:00"
    dependencies:
    - name: observability
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: sysmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: ycsbmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 2db30624468eed5b4f1bbe0867a085039dc17b9d12e0328592caff6bcf9b523e
    name: mongodb
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/mongodb-0.1.1.tgz
    version: 0.1.1
  observability:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 1.10.0
    created: "2021-11-13T01:25:09.250632738+02:00"
    description: The Observability stack of Frisbee. Installs Prometheus + Grafana
    digest: 3769419ed8f57a8a97d935573294f6f1ccd5850998a25819412808560a318f25
    home: https://github.com/bitnami/charts/tree/master/bitnami/common
    icon: http://new.sevenhillstechnology.com/wp-content/uploads/2021/01/undraw_programming_2svr.png
    name: observability
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/observability-0.1.1.tgz
    version: 0.1.1
  redis:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.251874376+02:00"
    dependencies:
    - name: observability
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: sysmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: ycsbmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 1202f1685706b173898d1483583232baa78e12655936703974f14e94bb1b562d
    name: redis
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/redis-0.1.1.tgz
    version: 0.1.1
  sysmon:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 1.10.0
    created: "2021-11-13T01:25:09.252125969+02:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts. This chart is not deployable by itself.
    digest: 93441b06864d85ee51c7ebb7ac4d96b050c4efdc9aa7187f1de2e55fe7340b0a
    home: https://github.com/bitnami/charts/tree/master/bitnami/common
    icon: http://new.sevenhillstechnology.com/wp-content/uploads/2021/01/undraw_programming_2svr.png
    name: sysmon
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/sysmon-0.1.1.tgz
    version: 0.1.1
  tikv:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.254563917+02:00"
    dependencies:
    - name: observability
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: sysmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    - name: ycsbmon
      repository: https://carv-ics-forth.github.io/frisbee/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 3f173c35bf504327fffa484c866fc72dbf665ae0001a5525174452fd7da703bc
    icon: https://tikv.org/img/logos/horizontal/color/tikv-horizontal-color.png
    name: tikv
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/tikv-0.1.1.tgz
    version: 0.1.1
  ycsbmon:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-13T01:25:09.255094462+02:00"
    description: A Helm chart for Kubernetes
    digest: 438319595ba537b9712f1b81cba0366caf51f529151da6dacafd165baced8359
    name: ycsbmon
    type: application
    urls:
    - https://carv-ics-forth.github.io/frisbee/charts/ycsbmon-0.1.1.tgz
    version: 0.1.1
generated: "2021-11-13T01:25:09.228890342+02:00"
