FROM prom/prometheus

# Use envsubst to replace ${var} or $var according to the values of the current environment variables.
RUN  wget https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-Linux-x86_64 && \
    chmod +x envsubst-Linux-x86_64
