{
 "title": "Prometheus Redis (by addr and host)",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_uptime,instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(redis_uptime,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Keyspace Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_keyspace_keys) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "bargauge",
   "description": "Total number of commands processed by the server",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_total_commands_processed) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Overview  $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Redis Up Time",
   "type": "stat",
   "description": "Redis Up Time",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(redis_uptime{instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Keys",
   "type": "stat",
   "description": "Total Keys ",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_keyspace_keys{instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_commands_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_clients{instance=\"$instance\"})",
     "legendFormat": "connected_clients"
    }
   ]
  },
  {
   "title": "Total Connection Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(redis_total_connections_received{instance=\"$instance\"})",
     "legendFormat": "Total Connections"
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "stat",
   "description": "Total Commands Processed",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(redis_total_commands_processed{instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_commands_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Error Replies",
   "type": "stat",
   "description": "Total number of issued error replies, that is the sum of rejected commands (errors prior command execution) and failed commands (errors within the command execution)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(redis_total_error_replies{instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_commands_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Commands Executed / Sec",
   "type": "timeseries",
   "description": "Number of commands processed per second",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Instantaneous OPS per sec",
     "expr": "max(redis_instantaneous_ops_per_sec{instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Per second",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "instantaneous_ops_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Redis CPU Usage",
   "type": "timeseries",
   "description": "User CPU consumed by the Redis server",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Uuser CPU",
     "expr": "max (irate(container_cpu_user_seconds_total{instance=\"$instance\"}[1m])) *100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "User",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_cpu_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    },
    {
     "expr": "max (irate(container_cpu_system_seconds_total{instance=\"$instance\"}[1m]))  *100\n",
     "legendFormat": "System"
    },
    {}
   ]
  },
  {
   "title": "Network Input / Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(redis_total_net_input_bytes{instance=\"$instance\"})",
     "legendFormat": "input_bytes"
    },
    {
     "expr": "- max(redis_total_net_output_bytes{instance=\"$instance\"})",
     "legendFormat": "output_bytes"
    }
   ]
  },
  {
   "title": "Total Command Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_cmdstat_calls{instance=\"$instance\"}",
     "legendFormat": "{{ command  }}"
    }
   ]
  },
  {
   "title": "Redis Memory Utilization",
   "type": "timeseries",
   "description": "Total number of bytes allocated by Redis using its allocator",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total Used Memory",
     "expr": "max(redis_used_memory{instance=~\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "mem_used",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    },
    {
     "expr": "max(redis_used_memory_lua{instance=~\"$instance\"})",
     "legendFormat": "mem_lua"
    },
    {
     "expr": "max(redis_used_memory_peak{instance=\"$instance\"})",
     "legendFormat": "mem_peak"
    },
    {
     "expr": "max(redis_used_memory_rss{instance=\"$instance\"})",
     "legendFormat": "mem_rss"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true
  },
  {
   "title": "Connected Slaves",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_connected_slaves{instance=\"$instance\"})",
     "legendFormat": "connected_clients"
    }
   ]
  },
  {
   "title": "Sync Full",
   "type": "stat",
   "description": "The number of full resyncs with replicas",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_sync_full{instance=\"$instance\"})",
     "legendFormat": "The number of full resyncs with replicas"
    }
   ]
  },
  {
   "title": "Sync Partial OK",
   "type": "stat",
   "description": "The number of accepted partial resync requests",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_sync_partial_ok{instance=\"$instance\"})",
     "legendFormat": "The number of accepted partial resync requests"
    }
   ]
  },
  {
   "title": "Sync Partial Error",
   "type": "stat",
   "description": "The number of denied partial resync requests",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_sync_partial_err{instance=\"$instance\"})",
     "legendFormat": "The number of denied partial resync requests"
    }
   ]
  },
  {
   "title": "Uptime per Role",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(redis_uptime{instance=\"$instance\"}) by (replication_role)",
     "legendFormat": "{{replication_role}}"
    }
   ]
  },
  { "title": "Redis Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Hit / Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(redis_keyspace_hitrate{instance=\"$instance\"})",
     "legendFormat": "redis_hitrate"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(irate(redis_keyspace_hits{instance=\"$instance\"}[1m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "max(irate(redis_keyspace_misses{instance=\"$instance\"}[1m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Now: Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_keyspace_keys{instance=~\"$instance\", host=~\"$host\"}) - sum (redis_expired_keys{instance=~\"$instance\", host=~\"$host\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_expired_keys{instance=~\"$instance\", host=~\"$host\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Total Evicted / Expired keys",
   "type": "graph",
   "description": " evicted_keys: Number of evicted keys due to maxmemory limit\n\n expired_keys: Total number of key expiration events",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_evicted_keys{instance=\"$instance\"})",
     "legendFormat": "evicted_keys"
    },
    {
     "expr": "sum(redis_expired_keys{instance=\"$instance\"})",
     "legendFormat": "expirted_keys"
    }
   ]
  },
  {
   "title": "Total Tracking Items",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_tracking_total_items{instance=\"$instance\"}",
     "legendFormat": "total_tracking_items"
    }
   ]
  }
 ]
}