{
 "title": "YCSB Services",
 "tags": [ "ycsb" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Real-time Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Operations ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(ycsb_count) by (instance)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Top Operations",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ycsb_count) by (operation)", "legendFormat": "{{operation}}" }
   ]
  },
  { "title": "Historical Clients Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Throughput (Queries Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "avg(ycsb_ops) by (instance)", "legendFormat": "{{ instance }}" },
    { "expr": "avg(ycsb_ops) ", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "max(ycsb_avg) by (instance)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Tail Latency (99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_99th) by (instance)", "legendFormat": "{{ instance }}" },
    { "expr": "avg(ycsb_avg) ", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Tail Latency (99.9)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_999th) by (instance)", "legendFormat": "{{ instance }}" },
    { "expr": "avg(ycsb_avg) ", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Tail Latency (99.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_9999th) by (instance)", "legendFormat": "{{ instance }}" },
    { "expr": "avg(ycsb_avg) ", "legendFormat": "Average" }
   ]
  },
  { "title": "Historical Operations Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "avg(ycsb_ops) by (operation)", "legendFormat": "{{ operation }}" },
    { "expr": "avg(ycsb_ops) ", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "max(ycsb_avg) by (operation)", "legendFormat": "{{ operation }}" }
   ]
  },
  {
   "title": "Tail Latency (99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_99th) by (operation)", "legendFormat": "{{ operation}}" },
    { "expr": "avg(ycsb_avg) ", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Tail Latency (99.9)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "avg(ycsb_999th) by (operation)", "legendFormat": "{{ operation }}" },
    { "expr": "avg(ycsb_avg) ", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Tail Latency (99.99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(ycsb_9999th) by (operation)",
     "legendFormat": "{{ operation }}"
    },
    { "expr": "avg(ycsb_avg) ", "legendFormat": "Average" }
   ]
  }
 ]
}