{
 "title": "MongoDB",
 "description": "Note for a official Grafana MongoDB plugin, please view:\nhttps://grafana.com/grafana/plugins/grafana-mongodb-datasource\n\nThis is a MongoDB Prometheus Exporter Dashboard. \nWorks well with https://github.com/dcu/mongodb_exporter\n\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(count (up{mon=~\"mongo\"}) by (instance))"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(count_command_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_document_inserted{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_queries_per_sec{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica Set Metrics for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "env"
  },
  {
   "title": "Member Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_replset_number_of_members{instance=\"$instance\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_replset_member_health{instance=\"$instance\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "timeseries",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_replset_member_state{instance=\"$instance\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Health metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_uptime_ns{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_available{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections_current{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Oplog Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=\"$instance\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Oplog Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(mongodb_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_ms{instance=\"$instance\"}[5m])/1000 or irate(node_disk_io_time_ms{instance=\"$instance\"}[5m])/1000)",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Reads Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  }
 ]
}